# Gradle and Android settings
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableBetaExpectActualClasses=true

# --- RELEASE SIGNING CREDENTIALS ---
SIGNING_KEY_ALIAS=ffmechanic_alias
SIGNING_KEY_PASS=ffmechanic@123
SIGNING_STORE_PASS=ffmechanic@123

# --- BASE URLS: CBP ---
URL_CBP_DEV=https://api-dev2.royalenfield.com/v3/
URL_CBP_UAT=https://api-uat2.royalenfield.com/v3/
URL_CBP_PROD=https://api.royalenfield.com/v3/

# --- BASE URLS: FF LAYER ---
URL_FF_DEV=https://cbpdev-in-api.royalenfield.com/
URL_FF_UAT=https://cbpuat-in-api.royalenfield.com/
URL_FF_PROD=https://cbp-in-api.royalenfield.com/

# --- BASE URLS: GRAPHQL ---
URL_GRAPHQL_SIT=https://connected-api-sit.royalenfield.com/graphql
URL_GRAPHQL_UAT=https://connected-api-sit.royalenfield.com/graphql
URL_GRAPHQL_PROD=https://connected-api.royalenfield.com/graphql

# --- DEVICE PROVISIONING & TELEMETRY ---
URL_PROVISION_DEV=https://cbp-in-dev.royalenfield.com/
URL_PROVISION_UAT=https://cbp-in-uat.royalenfield.com/
URL_PROVISION_PROD=https://cbp-in-api.royalenfield.com/

PATH_TOKEN_SIGN_DEFAULT_EU=cbp-regional/device-provisioning-service/v1/token/sign
PATH_TOKEN_SIGN_DEFAULT=cbpin/device-provisioning-service/v1/token/sign
PATH_TOKEN_SIGN_PROD=cbpin/device-provisioning-service/v1/token/sign

PATH_TELEMETRY_DEFAULT_EU=cbp-regional/telemetry-curr/current-value/
PATH_TELEMETRY_DEFAULT=cbpin/telemetry-curr/current-value/
PATH_TELEMETRY_PROD=cbpin/telemetry-curr/current-value/

# --- API KEYS ---
# Main App API Keys
API_KEY_DEV=your_dev_key_here
API_KEY_UAT=your_uat_key_here
API_KEY_PROD=aRO4J2rYcR7oCdPsnzESGFTTWVpM3vdodDY1hiOWqRU

# Specific Feature Keys
API_KEY_PROVISION=mkt0zXGgoNsf6i-4LzIqLaoovIIMJehBONkSGmcle70
API_KEY_OTA_DEV=WTJGdGNHRnBaMjVBVFdGdVpNM3ZkZWRZMWhpT1dxUlU
API_KEY_OTA_DEFAULT=68e99dce-52a6-4385-9fa9-1e85c24f942e

API_KEY_TELEMETRY_DEV=dGVsZW1ldHJ5LWN1cnJAMTIz
API_KEY_TELEMETRY_DEFAULT=dgKlKWwxYban74FXtKUEqQkWJG625c1SR7WP9rnc3b0

# admin alert Keys
ADMIN_PIN_ALERT_ID_DEV=MTM0Ojc4OjA
ADMIN_PIN_ALERT_ID_UAT=MTM0Ojc4OjA
ADMIN_PIN_ALERT_ID_PROD=NzcwOjc4OjA

# admin alert Keys
ADMIN_PIN_GENERATE_OTP_DEV=notify/otp/generate
ADMIN_PIN_GENERATE_OTP_UAT=notify/otp/generate
ADMIN_PIN_GENERATE_OTP_PROD=ffnotify/otp/generate

# admin alert Keys
ADMIN_PIN_VALIDATE_OTP_DEV=notify/otp/validate
ADMIN_PIN_VALIDATE_OTP_UAT=notify/otp/validate
ADMIN_PIN_VALIDATE_OTP_PROD=ffnotify/otp/validate

# sales App Keys
SALES_FORCE_APP_KEY_DEV=your_dev_key_here
SALES_FORCE_APP_KEY_UAT=a7d27504-4996-4c94-a279-4b9f2dcc0481
SALES_FORCE_APP_KEY_PROD=06b65da8-0c2a-400e-a927-2d17f9680e68
# sales Access Token Keys
SALES_FORCE_ACCESS_TOKEN_DEV=your_dev_key_here
SALES_FORCE_ACCESS_TOKEN_UAT=7R4z8C5T0nLc7a1utKXTDkNb
SALES_FORCE_ACCESS_TOKEN_PROD=3XDu9G0LrJplSm8CZSlPAJT3
# sales force ServerUrl
SALES_FORCE_SERVER_URL_DEV=your_dev_key_here
SALES_FORCE_SERVER_URL_UAT=https://mc3snfg-sfh7x8jmy5gw1rdk4zbq.device.marketingcloudapis.com/
SALES_FORCE_SERVER_URL_PROD=https://mc3snfg-sfh7x8jmy5gw1rdk4zbq.device.marketingcloudapis.com/

PLAY_STORE_SHA_256=81dd03e83151eeea58853d12c368d372af1b0dc6dd6129d7e849de5e5d8f1c1b

# Service manual access token
SERVICE_MANUAL_ACCESS_TOKEN_PROD=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbklkIjo1MDMwLCJ1c2VybmFtZSI6IlJFQWRtaW4iLCJyb2xlcyI6IkNMSUVOVCIsImlhdCI6MTYwMzM2NzM1OX0.SzF9XSj9mWUT2Oafb68HYOZVIo7Md4-aKPK0CeL3lho
